Assignemnt2 Completed
rishabh1164/javascript pull request #1
Opened 2023-08-16 05:07 UTC by rishabh1164

2023-08-16 19:09 UTC, ajay-nx requested changes

2023-08-16 19:09 UTC, ajay-nx commented on Assignment2.js
> +let num = Math.floor(Math.random()*10 ) + 1;
Please use const as you are not reassigning value to this variable. 
Please take care of naming convention & use meaningful variable names. 

ex - const randomNumber = Math.floor(Math.random() * 10) + 1;

2023-08-16 19:09 UTC, ajay-nx commented on Assignment2.js
> +let age = prompt("Enter your age");
Please use const instead of let here.

2023-08-16 19:09 UTC, ajay-nx commented on Assignment2.js
> +function numerical(value){
Indentation is not proper - Please install extension for the better indentation of your code.

2023-08-16 19:09 UTC, ajay-nx commented on Assignment2.js
> +//cheker is a function expression which takes a value as an argument and returns true if its even and false otherwise
if - else condition is un-necessary here - you can simply return the condition here - 

ex - const evenOddChecker = (value) => val % 2 === 0;

2023-08-16 19:09 UTC, ajay-nx commented on Assignment2.js
> +//Question 3 in Arrow Function
Naming convention & indentation is not proper.

2023-08-16 19:21 UTC, ajay-nx requested changes

2023-08-16 19:21 UTC, ajay-nx commented on Assignment2.js
> +
Please read more about JS file naming convention & rename this file & other tasks files accordingly. 

ex - assignmentTwo.js
        assignment2.js
        assignment-2.js
        assignment_2.js
        
  Let's discuss on this tomorrow.

2023-08-17 08:38 UTC, ajay-nx requested changes

2023-08-17 08:38 UTC, ajay-nx commented on assignment2.js
> +const randomNumber = Math.floor(Math.random() * 10) + 1;
AC - Simultaneous answers could not be same is not achieved.

2023-08-17 09:45 UTC, rishabh1164 commented on assignment2.js
> +const randomNumber = Math.floor(Math.random() * 10) + 1;
updated the program for question 1 .

2023-08-17 09:47 UTC, rishabh1164 commented on Assignment2.js
> +let age = prompt("Enter your age");
replaced let with const .

2023-08-17 09:59 UTC, ajay-nx approved these changes

2023-08-17 11:06 UTC, merged