Assignment 3 ( Arithmetic Operators , Patterns , even and odd numbers , prime numbers , Fibonaaci Series )
rishabh1164/javascript pull request #2
Opened 2023-08-16 12:40 UTC by rishabh1164

Solved Problems based on Arithmetic operators ,  even and odd numbers  and wrote programs to find prime numbers upto n.
Wrote Program for printing FIbonaaci Series .

2023-08-16 19:15 UTC, ajay-nx requested changes

2023-08-16 19:15 UTC, ajay-nx commented on Assignment2.js
> +//Question 1
This pull request should have only Assignment 3 changes. Please update the PR accordingly.

2023-08-16 19:15 UTC, ajay-nx commented on Assignment3.js
> +// created calculator arrow function which takes two numerical values and one character value ( that tells us which arithmetic operation needs to perform)
In this problem - It's better to use switch statement for more readability & maintainability.

2023-08-16 19:15 UTC, ajay-nx commented on Assignment3.js
> +// created calculator arrow function which takes two numerical values and one character value ( that tells us which arithmetic operation needs to perform)
**Indentation** of this file isn't proper & you can use **multiline comments** for better readability.

2023-08-17 08:51 UTC, rishabh1164 commented on Assignment2.js
> +//Question 1
updated PR ( only have assignment3 )

2023-08-17 08:52 UTC, rishabh1164 commented on Assignment3.js
> +// created calculator arrow function which takes two numerical values and one character value ( that tells us which arithmetic operation needs to perform)
used eslint and prettier for better indentation.
used multiline comments wherever needed .

2023-08-17 11:06 UTC, ajay-nx approved these changes

2023-08-17 11:07 UTC, merged